/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseTablePage: typeof import('./components/dynamics/tables/BaseTablePage.vue')['default']
    CreateReservation: typeof import('./components/reservations/CreateReservation.vue')['default']
    CreateTicket: typeof import('./components/tickets/CreateTicket.vue')['default']
    DynamicForm: typeof import('./components/dynamics/forms/DynamicForm.vue')['default']
    DynamicTable: typeof import('./components/dynamics/tables/DynamicTable.vue')['default']
    Footer: typeof import('./components/layouts/Footer.vue')['default']
    Header: typeof import('./components/layouts/Header.vue')['default']
    Pagination: typeof import('./components/dynamics/controls/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInputField: typeof import('./components/dynamics/controls/SearchInputField.vue')['default']
    Ticket: typeof import('./components/tickets/Ticket.vue')['default']
    UpdateReservation: typeof import('./components/reservations/UpdateReservation.vue')['default']
    UpdateTicket: typeof import('./components/tickets/UpdateTicket.vue')['default']
  }
}
